### ISSUE TITLE
how to replace the test datasets with other datasets?

### ISSUE THREAD

**Issue by Kara035** [jfkirk/tensorrec#100]
Hi,
I get the error **ModuleNotFoundError: No module named 'test.datasets'**
Would you be able to help where I can load the test.datasets?
I want to know what is the format I need to prepare for the dataset.
Is there any tutorial that you can provide to prepare the input dataset to load?
The get_book_crossing dataset I get from http://www2.informatik.uni-freiburg.de/~cziegler/BX/
is a zip file containing three datasets. Is that the same format I can prepare? Do I need to keep the file name the same as "BX-Book-Ratings","BX-Books", and "BX-Users"?
Thank you so much,
Kara

**Comment by jfkirk** [comment]
@Kara035 Are you still running in to this `ModuleNotFoundError`? If so, how did you install TensorRec? (pip, clone of the github repo, etc?)

**Comment by Kara035** [comment]
Hi,
No. I'm good for this one now. I found the dataset.py which I can switch to my own dataset.
Thank you so much for checking.
Kara

**Comment by jfkirk** [comment]
Great! I'm going to close this issue, too, then. Feel free to open a new issue with anything else that comes up!
