### ISSUE TITLE
dataset transformers for continuous features

### ISSUE THREAD

**Issue by Kara035** [jfkirk/tensorrec#101]
Hi,
The examples for get_book_crossing() converts all the features into categorical data. 
What if some features need to be considered as continuous? 
For example, for the age, will it be possible to transform it as a continuous field instead of a binary for each age? If so, what function I should use for the 'subcat_vectorizer' in the transformers?
Please correct me if I misunderstood the dataset.py, since I'm new to the tensorrec model.
Thank you so much,
Kara

**Comment by jfkirk** [comment]
Hey @Kara035 -- you understood dataset.py correctly. I turned ages categorical for simplicity's sake, but it could be a good idea to make the values continuous.

Transforming "age" in to a continuous variable can be done using different transformers from scikit. If you're so inclined, you could tweak the book crossing method to try this out. This continuous feature would be consumed by TensorRec just fine.
