### ISSUE TITLE
fit and save model

### ISSUE THREAD

**Issue by Kara035** [jfkirk/tensorrec#103]
Hi,
I see the configuration in the fit_and_eval(), but not in TensorRec().
Does the model automatically get saved after I run the fit_and_eval()? So when I call the model.predict_rank(), it will call the trained model?
What if I want to retrain the model for a different dataset?
Thank you so much for sharing this project. It is very helpful to have the codes ready for implementation based on all the algorithm!
Kara

**Comment by jfkirk** [comment]
Hey @Kara035 -- the models are stateful so, after falling `fit_and_eval` the model you passed in will be trained.

```python
model = TensorRec()

results = fit_and_eval(model=model, user_features=user_features, item_features=item_features, train_interactions=train_interactions, test_interactions=test_interactions)

# This model is now a fit model.
model.predict_rank(user_features=user_features, item_features=item_features)  
```

**Comment by Kara035** [comment]
Hi,
Thanks for the reply.
Would it be possible to continue training the model instead of a one time train? Let say if I have new records coming in, and want the model to continue learning. How would I do that?
Thank you in advance for all the support.
Kara

**Comment by jfkirk** [comment]
Hey @Kara035 -- that is how it works by default. Repeated calls to `fit()` for a given model will continue training on top of the existing model state.

```python
# Fit for 50 epochs
model.fit(epochs=50 ..... )

# Fit for another 50 epochs, 100 total
model.fit(epochs=50 ..... )
```
