### ISSUE TITLE
Different number of components for user and item representation

### ISSUE THREAD

**Issue by kj-lai** [jfkirk/tensorrec#104]
Hi, in TensorRec.TensorRec() is there an option to specify the number of components for user and item features separately?

For example, my user_feature is about 5 columns, whereas item_feature is about 15 columns, what n_components should i use? 5, 10, 15, or more than 15 ?

2nd Question:
In the keras_example, for generating baseline, is there a feature or method to do in in batches? because my interaction matrix (sparse type) is too large and causes OOM. My RAM is about 16GB and my interaction matrix is <10k users x 1.5M items>.

random_warm_result = eval_random_ranks_on_dataset(train_interactions, recall_k=100, precision_k=100, ndcg_k=100)
random_cold_result = eval_random_ranks_on_dataset(test_interactions, recall_k=100, precision_k=100, ndcg_k=100)

**Comment by jfkirk** [comment]
Hey @kj-lai -- the number of components you select is a hyperparameter to optimize: try out different values and see which perform the best. They have to be the same for users and items because the prediction function needs to consume two representations of the same size.

For the keras example, have you tried setting the `user_batch_size` parameter for `fit()`?

**Comment by kj-lai** [comment]
Thanks for your reply

Q1: What happens if I set my number of components more than the feature i have? let's say `n_component=20` when my features is only 5

Q2: the `eval_random_ranks_on_dataset()` is from `tensorrec.eval` section to generate random guesses, but it does not offer `user_batch_size` option. As for `fit()`, yes, i can do it in batches.

**Comment by jfkirk** [comment]
Q1: It would be no problem to have more components than features -- that would be an "overcomplete" situation, like an "overcomplete" auto-encoder. For some problems, that is perfectly appropriate.

Q2: Ah, you're right -- `eval_random_ranks_on_dataset()` doesn't have the ability to do batching. You could get it down to workable size by sampling users from your interactions/features to pass in to the eval method.
