### ISSUE TITLE
predict scores for specific user on specific products

### ISSUE THREAD

**Issue by Kara035** [jfkirk/tensorrec#106]
Hi,
In the intro_post.md
There's an example to predict scores for specific user.
`# Predict scores for user 75 on items 100, 101, and 102
predictions = model.predict(user_ids=[75, 75, 75],
                            item_ids=[100, 101, 102],
                            user_features=user_features,
                            item_features=item_features)`
However, I got an error on running the code:
TypeError: predict() got an unexpected keyword argument 'user_ids'
And I look at the predict() in tensorrec.py, there's no params for user_ids or item_ids.
Could you please advice how I can use the function to call recommendation for specific user?
Thank you so much,
Kara

**Comment by jfkirk** [comment]
Hey @Kara035 ! That example is from an old blog post, and the API has changed since then. Now, you can the predictions for specific users and items by only passing the features for those users and items to `predict()`.

Something like:
```python
model.predict(user_features=user_features[75], item_features=item_features[100:103])
```
