### ISSUE TITLE
How do you create Item Features which includes Indicator & Metadata?

### ISSUE THREAD

**Issue by kj-lai** [jfkirk/tensorrec#107]
Let's say for example:
interaction matrix = 1000 users x 20000 items
density=0.5, pos_int_ratio=1, num_user_features=3. num_item_features=10, n_features_per_user=3, n_features_per_item=10

Question 1:
How would you generate the item features so that it's format will be 20000 x 20010 sparse matrix like in lightfm's item feature builder?

Question 2:
Should I normalize the item features for each item?

**Comment by jfkirk** [comment]
Hey @kj-lai !

I'm not familiar with LightFM's item feature builder. I have used this to generate dummy features shaped like that, though:

```python
def generate_dummy_data_with_indicator(num_users, num_items, interaction_density, n_user_metadata_features=40, n_item_metadata_features=40):

    n_user_features = int(num_users + n_user_metadata_features)
    n_item_features = int(num_items + n_item_metadata_features)
    n_interactions = int((num_users * num_items) * interaction_density)

    user_features = sp.lil_matrix((num_users, n_user_features))
    for i in range(num_users):
        user_features[i, i] = 1  # Indicator feature
        for j in range(n_user_metadata_features):
        	user_features[i, num_users+j] = random.uniform(-1.0, 1.0)  # Metadata features

    item_features = sp.lil_matrix((num_items, n_item_features))
    for i in range(num_items):
        item_features[i, i] = 1  # Indicator feature
        for j in range(n_item_metadata_features):
        	item_features[i, num_items+j] = random.uniform(-1.0, 1.0)  # Metadata features

    interactions = sp.lil_matrix((num_users, num_items))
    for i in range(n_interactions):
        interactions[random.randrange(num_users), random.randrange(num_items)] = random.uniform(0.0, 10.0)

    return interactions, user_features, item_features
```

Normalizing features is a good idea if you are using linear representations and have lots of metadata features. This helps prevent wild predictions for items that have many non-zero metadata features.

Hope this helps! I'll leave this issue open for a few days.

**Comment by kj-lai** [comment]
Thank for your reply, this is very helpful, I'm gonna close this issue now.
