### ISSUE TITLE
Tensorrec environment issue 

### ISSUE THREAD

**Issue by Jesontheg6** [jfkirk/tensorrec#110]
@jfkirk thanks for building tensorrec. I tried runing the basic example code, but I faced this issue. I have read some of the issues but none of it solved the problem. I even uninstalled my tensorflow to install the TensorFlow 1.7.0. so that its compatible. But it still throw the same error. Hope you can help. 

`Traceback (most recent call last):
  File "tensorrec.py", line 2, in <module>
    import tensorrec
  File "/Users/leejunzhen/tensorrec.py", line 5, in <module>
    model = tensorrec.TensorRec()
AttributeError: module 'tensorrec' has no attribute 'TensorRec'`

**Comment by jfkirk** [comment]
hey @Jesontheg6 ! Can you describe how you installed TensorRec? And are you running the exact example code from the GitHub landing page?

**Comment by Jesontheg6** [comment]
Hey @jfkirk Yes I am running the exact example code from the GitHub landing page. And I also did pip install tensorrec

**Comment by jfkirk** [comment]
Hey @Jesontheg6 -- I've been trying to reproduce this issue but haven't been able to so far.

Could you tell me more about your environment? What version of python are you on? Can you dump the contents of `pip freeze` for me?

**Comment by jfkirk** [comment]
Closing for now -- feel free to open a new issue if this problem persists.
