### ISSUE TITLE
Upgrade tensorflow dependency

### ISSUE THREAD

**Issue by elgalu** [jfkirk/tensorrec#113]
How tight is tensorrec to this `1.7.0` tensorflow version?

https://github.com/jfkirk/tensorrec/blob/fc6d76dda0398cb65bc1e6ea740e9f2e160aa81a/setup.py#L21

Would it be possible to relax the dependency, e.g. >=1.7.0,<1.10 ?

That would probably require using a TravisCI matrix or tox to test against multiple versions though.

**Comment by jfkirk** [comment]
Hey @elgalu ! Yes, that is a good idea. I'll take some time to see if the relaxed dependency breaks anything.

**Comment by jfkirk** [comment]
Merged #114 which lets any TF >= 1.7 run TensorRec.

I noticed that the tests are significantly slower in TF 1.12, which merits looking in to further.

**Comment by jfkirk** [comment]
I've release 0.26.0 which has the dependency range -- closing.
