### ISSUE TITLE
Typo in example check_movielens_losses.py

### ISSUE THREAD

**Issue by MKhere** [jfkirk/tensorrec#115]

**Comment by jfkirk** [comment]
Hey @MKhere - thanks for reporting! 

`Euclidean` is the correct spelling, and all of TensorRec has been updated with the correct spelling. but this hasn't been released yet. If your copy of `check_movielens_losses.py` is from GitHub master but you're on TensorRec 0.25.9 locally, you'd run in to a naming mismatch.

**Comment by jfkirk** [comment]
Released 0.26.0 which has the correct spelling.
