### ISSUE TITLE
update for numpy 1.15 and scipy 1.1

### ISSUE THREAD

**Issue by armando-fandango** [jfkirk/tensorrec#117]

**Comment by gfawcett22** [comment]
+1 the inability to use the scipy wheel for installation is preventing me from using tensorrec

**Comment by jfkirk** [comment]
(apologies for the delay, I've been on vacation)

This is my top priority now. I'm looking in to updating these reqs and will get an update out ASAP.

**Comment by jfkirk** [comment]
Fix merged -- will go out with next release
