### ISSUE TITLE
how to export the model?

### ISSUE THREAD

**Issue by Composmentis** [jfkirk/tensorrec#12]
Hey James,

It is cool. One quick question, How do we export the model and query it on runtime? Because the best of using user and product feature is that when there is a new user who is not part of training set should also have product scored.

Thanks

**Comment by jfkirk** [comment]
Hey @Composmentis ! We are still building convenience methods for saving and loading models. We'll be tracking that work on https://github.com/jfkirk/tensorrec/issues/8

I expect that to be merged within the week.

Closing as duplicate

**Comment by borisrev** [comment]
Hi James,

I'm still unclear on @Composmentis 's initial question, i.e. how does saving/loading models enable feeding a previously unseen user to an already trained model with tensorrec?

Thanks!

**Comment by jfkirk** [comment]
Hey @borisrev -- A user is simply a collection of feature values, so a TensorRec does not know or care if it has seen the user in training.

I interpreted the initial question to mean "I have trained a TensorRec model and saved it. In the future, I will want to load it and get predictions for new users." The missing link, at the time of the initial question, is that TensorRec did not have methods for saving and loading the models.

**Comment by borisrev** [comment]
Let's say you're using an identity matrix for the user matrix when training as in the MovieLens example. After training, if you want to pass a new user to predict() along with same item_features used in training, what dimensions would then be appropriate for the new user_features matrix? A row of all 0s with the same number of columns as the user matrix used during training?

**Comment by jfkirk** [comment]
Ahh sorry I was unclear -- A TensorRec model does not know or care if it has seen the user in training _unless_ the system is built with "Indicator Features". In the scenario you've outlined, the identity matrix for users is a set of indicator features, so all users will need to be present at fit() time.

The number of user/item features must be the same both at fit() and predict() time.

The counter-example would be the Book Crossing dataset with user_indicator and item_indicator set to False. In this case, the features are only metadata and the TensorRec model would not care if the user/item was present during training.
