### ISSUE TITLE
Negative interactions with WMRB

### ISSUE THREAD

**Issue by luiscastro193** [jfkirk/tensorrec#123]
This is actually a question about the theory behind the framework but I hope that's ok.

I have some experience with recommendation systems and it has become clear to me that in practice RMSE loss functions aren't good for them, so I really like the WMRB loss function. But it looks like it works only for implicit (positive) feedback. If an user have explicitly expressed that he dislikes an item, can't I use that information for training?

**Comment by luiscastro193** [comment]
Totally. I don't have the knowledge to write said function yet but that would indeed solve the problem.

**Comment by jfkirk** [comment]
Great! Closing now -- feel free to open new issues if you have more questions.
