### ISSUE TITLE
question: new user_interactions

### ISSUE THREAD

**Issue by martende** [jfkirk/tensorrec#137]
Hi and thanks for the great project, may be the question was already here but i can not find it . I 
whold like to implement prediction for some new user with some known interactions on known products . Currently all model functions accept `user_features`  `item_features` which are identity matrixes for the simple case : 

I can extract the info for some existing user :

`model.predict(user_features=user_features[75], item_features=item_features[100:103])
`
but i can not do something like this: 

```
model.predict(user_features=zero vector , item_features=item_features, user_interactions = [
0 0 0 ... 1 ... 1 
] )

```
for the new customer that likes 2 products.

**Comment by jfkirk** [comment]
Hey @martende ! Is this the situation you're in:

1. You train a TensorRec model for a large number of users. The user_features and item_features are identity matrices.
2. You get a new user who has interactions.
3. You want to predict recommendations for the new user based on their interactions.

Is this correct?

**Comment by martende** [comment]
Yes this is correct.

**Comment by jfkirk** [comment]
@martende TensorRec does not support this directly -- this new user, in this case, was not present during training so the model could not learn a user representation to make recommendations for them.

You can get around this with some logic wrapping TensorRec to create a user representation based on the interactions. It could look something like this psuedocode:

```
# Get item reprs for interacted items
interacted_item_reprs = [
    model.predict_item_representation(item_features[interacted_item_id])
    for interacted_item_id in new_user_interactions
]

# Synthesize a user repr and get all item reprs
synthetic_user_repr = sum(interacted_item_reprs)
all_item_reprs = model.predict_item_representation(item_features)

# Predict by multiplying the synthetic user repr and all the item reprs
# This only works if the prediction function is DotProduct (the TensorRec default)
predictions = synthetic_user_repr * all_item_reprs
```

Does this make sense?

**Comment by martende** [comment]
Thanks jfkirk,

Do you mean that I can construct new `user_representation` just as a sum of all `item_representations` for all interactions without any norming at the end ? I have got this intuition but i have no idea why it should work.

I have seen that implicit  https://github.com/benfred/implicit project is solving some linear equation for construction user representation for some straitforvard SVD prediction .

**Comment by jfkirk** [comment]
Hey @martende -- you shouldn't need to normalize the synthetic user_representation because the vector's magnitude is irrelevant when ranking. If you normalized it, you'd get the same ranking back. If you care about the precise predicted values, though, then you may want to normalize.

You also may want to explore weighting the inputs, though. If one interaction has weight `3` and another interaction has weight `5` you can to multiply those item reprs by a scalar weight before summing them so the interaction with higher weight has a bigger impact on the resulting user repr.

**Comment by Jyang772** [comment]
> Thanks @jfkirk,
> 
> Do you mean that I can construct new `user_representation` just as a sum of all `item_representations` for all interactions without any norming at the end ? I have got this intuition but i have no idea why it should work.
> 
> I have seen that implicit https://github.com/benfred/implicit project is solving some linear equation for construction user representation for some straitforvard SVD prediction .

Hi @jfkirk, could you explain why the new predicted user representation is the sum of the predicted item representations of items the new user has interacted with?
