### ISSUE TITLE
how to get `ratings.csv` file

### ISSUE THREAD

**Issue by mabodx** [jfkirk/tensorrec#141]
For the `examples/getting_started.py`
https://github.com/jfkirk/tensorrec/blob/b73977b69723110c3d79e0d62ad8a1db43dc7a5d/examples/getting_started.py#L16

how to get `ratings.csv` file which is in line 16 of above file.

**Comment by jfkirk** [comment]
You can download the files here: https://grouplens.org/datasets/movielens/

There's a blog post going through this example here: https://towardsdatascience.com/getting-started-with-recommender-systems-and-tensorrec-8f50a9943eef

I'm going to leave this open until I've added the links to the example file.

**Comment by jfkirk** [comment]
Done. Thanks!

https://github.com/jfkirk/tensorrec/commit/3e7dfe8962e8d9f78fc9032dfd86ebf421dd3505

**Comment by mabodx** [comment]
Nice. Thanks so much.
