### ISSUE TITLE
Dont use % for format

### ISSUE THREAD

**Issue by mkoryak** [jfkirk/tensorrec#16]
I dont know why, but everyone agrees that its bad:

<img width="580" alt="screen shot 2018-02-22 at 10 44 01 pm" src="https://user-images.githubusercontent.com/383817/36576942-0a5e7b84-1822-11e8-8826-bfdab59bf4e6.png">

**Comment by jfkirk** [comment]
Well, if our most holy commander decrees it...

**Comment by jfkirk** [comment]
https://github.com/jfkirk/tensorrec/commit/4ae14fd8deb26865209f7616ede6f8273f9f60f6
Our most holy commander shall be pleased.
