### ISSUE TITLE
Methods should be alphabetized

### ISSUE THREAD

**Issue by ewyler** [jfkirk/tensorrec#17]
How is anyone supposed to find anything?

Your code is like this cat currently:

![image](https://user-images.githubusercontent.com/2191725/36601263-b32ec682-1882-11e8-9d6d-c942e5186c5e.png)

**Comment by mkoryak** [comment]
Every line of cod should be alphbetized. It might no longer be parsable by a computer, but we all know that cod is not really meant to be read by computers.

**Comment by alexzahn** [comment]
Agreed, this is a sensible request.

**Comment by jfkirk** [comment]
Following PR#XVIII, all methods have been renamed in cyrillic and alphabetized. Closing for now.
