### ISSUE TITLE
Implement WMRB

### ISSUE THREAD

**Issue by jfkirk** [jfkirk/tensorrec#2]
Paper: http://ceur-ws.org/Vol-1905/recsys2017_poster3.pdf

Suggestion from Saúl Vargas @saulvargas

**Comment by saulvargas** [comment]
Hi!

In addition to removing the |Y|/|Z| term in Eq. 4 in the paper, the other trick I did was disregarding the I(y' \in \hat{y}) term in the same formula as, in practice, it rarely takes the value of 0 (for sparse datasets with large number of items, naturally). That should make the implementation a piece of cake. I also observed that a value of |Z| = 10 gives quite good performances, although that may arguably depend on the dataset.

Hope it helps.

Cheers,
Saúl

**Comment by umang-01** [comment]
Any updates on this?

**Comment by jfkirk** [comment]
Hey @umang-01 - diving in to this today, will update with in the week.

**Comment by jfkirk** [comment]
I added WMRB loss: https://github.com/jfkirk/tensorrec/commit/2efc01e083f6e7473b6bd84d17547ac38ae22833

I experiment with-and-without the final logarithm step and got much better results without the logarithm, so I left it commented out.

```
from tensorrec import TensorRec
from tensorrec.eval import fit_and_eval
from tensorrec.loss_graphs import separation_loss, wmrb_loss
from test.datasets import get_movielens_100k

train_interactions, test_interactions, user_features, item_features = get_movielens_100k()

model_baseline = TensorRec()
print(fit_and_eval(model_baseline, user_features, item_features, train_interactions, test_interactions, {'epochs': 1000}))

model_separation = TensorRec(loss_graph=separation_loss)
print(fit_and_eval(model_separation, user_features, item_features, train_interactions, test_interactions, {'epochs': 1000}))

model_wmrb = TensorRec(loss_graph=wmrb_loss)
print(fit_and_eval(model_wmrb, user_features, item_features, train_interactions, test_interactions, {'epochs': 1000}))```
yields
```
(0.19826102103939364, 0.011927194860813705) # RMSE
(0.21846470208354574, 0.012805139186295503) # Separation
(0.23483778593521634, 0.013693790149892934) # WMRB
```
These quick-and-dirty results (recall at 100, precision at 100) look good on movielens 100k

**Comment by umang-01** [comment]
@jfkirk Thanks a ton for the quick help. 👍
