### ISSUE TITLE
Methods should be ordered by lines of code within those methods

### ISSUE THREAD

**Issue by alexzahn** [jfkirk/tensorrec#22]
In cases of the same amount of lines of code, you should default to the order in which you wrote them.

**Comment by ewyler** [comment]
I think it would be more inline with industry standards to order by the _average age_ of all lines of cod in a given method

**Comment by jfkirk** [comment]
Merged PR#三四七 which, instead, cuts down all methods to a certain length based on position in the class.
Closing for now.
