### ISSUE TITLE
Weight normalization should be applied once per epoch

### ISSUE THREAD

**Issue by jfkirk** [jfkirk/tensorrec#30]
...not once per batch. What were you thinking, Jimmy!?

**Comment by mkoryak** [comment]
Maybe you should stop talking to your self

**Comment by mkoryak** [comment]
You have issues

**Comment by jfkirk** [comment]
If I don't talk to myself, who will?

**Comment by jfkirk** [comment]
Actually making weight reg only happen once per epoch turned out to be expensive, especially in the case where there is one batch per epoch. This is because it required two separate calls to the tf session every epoch. Instead, we resolved this by having the alpha parameter scale down exponentially based on the number of batches in the epoch.
