### ISSUE TITLE
Add API to retrieve projected user/item biases

### ISSUE THREAD

**Issue by jfkirk** [jfkirk/tensorrec#38]
Could be useful to examine item biases, for example.

- [ ] Add `predict_user_bias` and `predict_item_bias` API method to `TensorRec`
- [ ] Add hooks to `projected_user_biases` and `projected_item_biases` in `TensorRec` that can be used by the new API and for saving/loading
- [ ] Add tests for the new prediction methods

**Comment by jfkirk** [comment]
@ThoseGrapefruits you expressed interest via Slack -- let me know if you want to take a stab at this!

**Comment by ThoseGrapefruits** [comment]
Yep, sounds good!

**Comment by ThoseGrapefruits** [comment]
Not sure when you’re getting back from 🇸🇪👨‍👩‍👧‍👦🔨 but I have a couple intro questions already:

1. What’s the workflow for setting up the environment and running tests? I’ve been out of the Python environment for too long and all I remember is `pip install -r requirements.txt` and I’m not sure even that is right in this context.
2. Any style requirements? I noticed a 120-char line limit seems standard.

**Comment by jfkirk** [comment]
Hey @ThoseGrapefruits ! 

1. After cloning, you should be able to run the tests by stepping through
```
pip install -r requirements.txt
pip install -r requirements_test.txt
nosetests test/
```

2. 120-char line limit is correct (you can find it defined in setup.cfg). Beyond that, if Flake passes I'm probably comfortable with the style. I'm also a big fan of NumPy's commit message standards: https://docs.scipy.org/doc/numpy-1.13.0/dev/gitwash/development_workflow.html

3. Currently TensorRec is checked for compatibility with Python 2.7 and 3.6.1 -- either one should work for your development, just make sure to check both (Travis will check both on your PR, too).

Thanks!

**Comment by ThoseGrapefruits** [comment]
All sounds good.

I got it working in a virtualenv, but had to use `python -m nose test/` to run tests instead. Anyways, it works, and all 58 tests passed for me. Thanks!

I'll let you know when I have other questions :)
