### ISSUE TITLE
Values in interaction matrix

### ISSUE THREAD

**Issue by mmmmming18** [jfkirk/tensorrec#6]
Hi jfkirk, thanks for the hard work! 

The values in the interaction matrix have to be in (-1, 0, 1) or they can be any integer numbers?

**Comment by jfkirk** [comment]
Hey @mmmmming18 ! It depends on the loss function you plan to use.

If you use `rmse_loss`, any float or integer values will work -- TensorRec will function as a regressor and attempt to estimate those values directly.

If you use `separation_loss`, any float or integer value will work but any information besides positive/negative will be lost as this loss function simply treats interactions as positive or negative.

If you use `wmrb_loss`, all negative interactions are ignored and only positive interactions are considered, but the magnitude of the positive interactions is ignored, so (0, 1) is fine.

If you use a custom loss function then whatever logic you put in will handle the interactions so it is up to you.

I should add better documentation for this -- I'll close the issue once I have.

**Comment by jfkirk** [comment]
Pushed https://github.com/jfkirk/tensorrec/commit/710b692df48c7e5256f22901f289ec1c27a021d1 -- closing this issue for now.

**Comment by umang-01** [comment]
Hi @jfkirk, as per the above explanation for valid values in different loss functions, the model suits well for explicit rating recommendations. 
However, if we only have implicit feedback (ie. impressions(Yes/No), product views and, orders), I'm not sure if wmrb_loss or separation_loss could account for this information together. I've read the wmrb paper which states it's benefit for item ranking problem with an implicit feedback.

I'm trying to build RecSys for an E-commerce solution. It'd be of great help if you can suggest a way to use all the feedback in the model.

**Comment by jfkirk** [comment]
You should be able to use any of these loss functions with implicit feedback. Once you figure out which of these implicit signals are positive and which are negative, you can use those as interactions. 

If some implicit signals are _more_ positive or _more_ negative than others, you will want to use RMSE and figure out what magnitudes are appropriate through experimentation.
