### ISSUE TITLE
Importing tests.datasets fails

### ISSUE THREAD

**Issue by nikisix** [jfkirk/tensorrec#63]
On a fresh install of tensorrec and tf
tensorflow==1.8.0
tensorrec==0.25.1

(prototype) examples❯ python plot_movielens.py                                                                                                                          tensorrec/git/master

Traceback (most recent call last):
  File "plot_movielens.py", line 16, in <module>
    from test.datasets import get_movielens_100k
ImportError: No module named datasets

pulled down the entire repo and am in the examples directory

**Comment by jfkirk** [comment]
Hey @nikisix -- try going one level up and running 
`PYTHONPATH=. python examples/plot_movielens.py`

That may fail on some example-specific requirements. To get those, run `pip install -r requirements_test.txt`.

Let me know if that works!

Assigning to myself to make requirements/paths more clear.

**Comment by nikisix** [comment]
(prototype) ❯ PYTHONPATH=.                                                                                                                                               
(prototype) ❯ python examples/plot_movielens.py                                                                                                                          
Traceback (most recent call last):
  File "examples/plot_movielens.py", line 16, in <module>
    from test.datasets import get_movielens_100k
ImportError: No module named datasets

**Comment by jfkirk** [comment]
A `PYTHONPATH=.` declaration is scoped to just the one statement. Try putting it all on one line:
`PYTHONPATH=. python examples/plot_movielens.py`

**Comment by nikisix** [comment]
ok, worked!

**Comment by jfkirk** [comment]
Great! Let me know if you run in to anything else.

**Comment by nikisix** [comment]
Any way to get around needing to set path with every execution? I checked and my python path is already set to "."

(prototype) ❯ echo $PYTHONPATH                                                                                                                                          
.

**Comment by jfkirk** [comment]
If you have IPython, it will handle the PYTHONPATH appropriately without a declaration.
`ipython examples/plot_movielens.py`
