### ISSUE TITLE
get_book_crossing crashes

### ISSUE THREAD

**Issue by borisrev** [jfkirk/tensorrec#67]
I believe all relevant packages are up to date running on python 3.6.5

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-14-bf8d6ad719d6> in <module>()
>      29 train_interactions, test_interactions, user_features, item_features, _ = get_book_crossing(user_indicators=False,
>      30                                                                                            item_indicators=True,
> ---> 31                                                                                            cold_start_users=True)
>      32 
>      33 # Establish baseline metrics with random ranks for warm and cold start users
> 
> <string> in get_book_crossing(min_positive_score, min_interactions_per_book, user_indicators, item_indicators, cold_start_users, cold_start_items)
> 
> /usr/local/lib/python3.6/site-packages/sklearn/pipeline.py in fit_transform(self, X, y, **fit_params)
>     737             delayed(_fit_transform_one)(trans, weight, X, y,
>     738                                         **fit_params)
> --> 739             for name, trans, weight in self._iter())
>     740 
>     741         if not result:
> 
> /usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self, iterable)
>     777             # was dispatched. In particular this covers the edge
>     778             # case of Parallel used with an exhausted iterator.
> --> 779             while self.dispatch_one_batch(iterator):
>     780                 self._iterating = True
>     781             else:
> 
> /usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in dispatch_one_batch(self, iterator)
>     623                 return False
>     624             else:
> --> 625                 self._dispatch(tasks)
>     626                 return True
>     627 
> 
> /usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in _dispatch(self, batch)
>     586         dispatch_timestamp = time.time()
>     587         cb = BatchCompletionCallBack(dispatch_timestamp, len(batch), self)
> --> 588         job = self._backend.apply_async(batch, callback=cb)
>     589         self._jobs.append(job)
>     590 
> 
> /usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py in apply_async(self, func, callback)
>     109     def apply_async(self, func, callback=None):
>     110         """Schedule a func to be run"""
> --> 111         result = ImmediateResult(func)
>     112         if callback:
>     113             callback(result)
> 
> /usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py in __init__(self, batch)
>     330         # Don't delay the application, to avoid keeping the input
>     331         # arguments in memory
> --> 332         self.results = batch()
>     333 
>     334     def get(self):
> 
> /usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self)
>     129 
>     130     def __call__(self):
> --> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
>     132 
>     133     def __len__(self):
> 
> /usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0)
>     129 
>     130     def __call__(self):
> --> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
>     132 
>     133     def __len__(self):
> 
> /usr/local/lib/python3.6/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, weight, X, y, **fit_params)
>     579                        **fit_params):
>     580     if hasattr(transformer, 'fit_transform'):
> --> 581         res = transformer.fit_transform(X, y, **fit_params)
>     582     else:
>     583         res = transformer.fit(X, y, **fit_params).transform(X)
> 
> /usr/local/lib/python3.6/site-packages/sklearn/pipeline.py in fit_transform(self, X, y, **fit_params)
>     281         Xt, fit_params = self._fit(X, y, **fit_params)
>     282         if hasattr(last_step, 'fit_transform'):
> --> 283             return last_step.fit_transform(Xt, y, **fit_params)
>     284         elif last_step is None:
>     285             return Xt
> 
> TypeError: fit_transform() takes 2 positional arguments but 3 were given

**Comment by jfkirk** [comment]
Hey @borisrev ! Thanks for reporting. Can you confirm for me which version of scikit-learn you are currently running? I'll try to reproduce on my end.

**Comment by borisrev** [comment]
0.19.1

Thanks for all the great work on tensorrec and your attention on this!

**Comment by jfkirk** [comment]
Also thanks for the kind words :)

**Comment by jfkirk** [comment]
Hey @borisrev -- I've updated the scikit dependency and hacked around the LabelBinarizer changes in 0.19.1: https://github.com/jfkirk/tensorrec/commit/b6caaca984068a352142d7c14f7c84c22f503a94

This will go out with the next release.

Closing for now -- let me know if you run in to anything else!
