### ISSUE TITLE
Document the difference with the LightFM package

### ISSUE THREAD

**Issue by rragundez** [jfkirk/tensorrec#69]
I'm missing what is the difference  from https://github.com/lyst/lightfm 
and for which cases I would use tensorrec instead of lightfm

**Comment by jfkirk** [comment]
LightFM and TensorRec are very similar -- LightFM was the inspiration for TensorRec and I've used LightFM extensively.

The difference comes from the ability to build and customize your representation, prediction, and loss functions in TensorRec. If you build a TensorRec model with linear embedding representations and dot-product prediction, they're equivalent algorithms. In fact, if you're doing so, I'd advise you to work with LightFM as it is a more mature package. 

If you need to customize that system, though, that is where TensorRec comes in.

Hope that helps! Closing for now -- feel free to reopen if you have more questions.

**Comment by rragundez** [comment]
what do you mean with linear embeddings representations?

**Comment by jfkirk** [comment]
The "representation" function is responsible for calculating a latent representation of the user based on the user's features. 

In this diagram, it is the `user_repr_graph` in the top left: https://raw.githubusercontent.com/jfkirk/tensorrec/master/examples/system_diagram.png

The representation graphs which are available by default are here: https://github.com/jfkirk/tensorrec/wiki/Representation-Graphs

If you use the top one, `LinearRepresentationGraph`, for both users and items then your system will be equivalent to LightFM.
