### ISSUE TITLE
more about applying TensorRec on session-based implicit feedback data

### ISSUE THREAD

**Issue by hodaraad** [jfkirk/tensorrec#76]
Thank you for your prompt and thoughtful answer on my previous question regarding session-based scenario (I could not find an option for reopening an issue and hence I opened a new one). So, if we ignore the order of items in the session, 

- is it still possible to implement some of those pairwise ranking loss functions introduce in this paper[https://arxiv.org/pdf/1511.06939.pdf] in TensorRec?

- How about implementing simpler methods such as a simple matrix factorization method such as the one based on Alternating least-square options used in this paper[http://yifanhu.net/PUB/cf.pdf]? I'm not clear what I should give as loss function and possibly embedding?

- Can you provide more example for legit options for item/user representation graph?

- How TensorRec performs in terms of sociability on big datasets?

thanks

**Comment by jfkirk** [comment]
Hey @hodaraad ! I'm glad to be of help.

For pairwise loss functions, we've already implemented WMRB which is similar to BPR and TOP1 -- it samples a batch of negative items and compares those to the positive items for that user. The transform is a bit different (BPR uses log loss, WMRB is a hinge) but you may be able to re-tool the WMRB graph to do either. In fact, we should add BPR to the available loss graphs.

For a close parallel to ALS, you could use RMSE loss with linear representation graphs. If you want to calculate loss for every possible (user, item) pair, use RMSEDense. If you only want to calculate for (user, item) pairs with non-0 interactions, use regular RMSE. The (A)lternating part of ALS isn't necessary, as TensorRec is learning both representations continually through SGD. For what its worth, I've found that RMSE is only useful for few recommendation problems, and pairwise losses (like WMRB) are almost always more effective.

The only good examples of representation graphs I have are those in the `representation_graphs` module and in the `examples` files. If you cook up one of your own, feel free to PR it or even just let me know!

I've scaled up TensorRec models to 100k items and 4m+ users on my MacBook. If you're scaling up that far or farther, try using the `user_batch_size` parameter to `fit()` to help keep things running.

I'll leave this issue open for a few days in case you have any more questions. Thanks again for your great questions!

**Comment by jfkirk** [comment]
hey @hodaraad ! I'm going to close this now. Feel free to open a new issue if you have any more Qs.
