### ISSUE TITLE
add dynamic feature for user and item to interaction?

### ISSUE THREAD

**Issue by cwyalpha** [jfkirk/tensorrec#78]
I'm building a TV recommend system. User feature is user_ID+Location, item feature is item_ID+tag+release_time. And in my system, item in different tags may have different time sensitive. For example, users will not watch old news, but old movies will be OK. 

When user click/watch a item, I want to add past 5 clicks/watches item IDs to user feature, and (watch_time - item_release_time) to item feature.
So at each interaction, new user feature  will be user_ID+Location+[past 5 clicks/watches item IDs], and new item feature will be item_ID+tag+release_time+(watch_time - item_release_time).
Is there any way to add dynamic feature for user and item to interaction?

One idea is to make user feature and item feature unique for each interaction, if there is N interactions, there will be N users and N items, and interaction matrix will be N*N diagonal matrix. Will this idea work? Or is there any other simple solution?

Thank you.

**Comment by jfkirk** [comment]
Hey @cwyalpha ! Great question.

Adding this kind of dynamic information is a bit of a departure from how TensorRec was constructed, but you may be able to make it work.

You could add the past 5 clicks/watches as user features. If you did this, your user feature size would be (num_user_ids + num_locations + num_item_ids). This would allow the system to learn how recently selected content could impact recs for a given user.

Adding (watch_time - item_release_time) would be more complicated -- you'd need to replicate the item for each user who has watched it and set the value in that row to the appropriate value for that user. This could cause the item features to become quite large.

Your intuition about diagonalizing the interactions is correct. This solution may work for you, but could have problems scaling when you have a large number of interactions. This may also break some assumptions for using the sampled loss functions, like WMRB.

If you give this a shot, please let me know! I'd be interested to hear if it was successful for you.

I'll leave this issue open for a few days in case you have more questions.
