### ISSUE TITLE
number of tastes in model

### ISSUE THREAD

**Issue by pierrehabte2017** [jfkirk/tensorrec#79]
Hi !
I did not get what is the interpretation of the number of tastes in the model. 
Does the n_taste impact how user embeddings are learned ?

**Comment by jfkirk** [comment]
Hey Pierre -- thanks for your question.

The number of tastes defines the number of embeddings learned per user. If `n_tastes=5` then each user will have 5 separate representations/embeddings.

You can read more about the thinking behind it here: https://arxiv.org/pdf/1711.08379.pdf

Hope that helps! I'll leave this issue open for a few days if you have more questions.

**Comment by pierrehabte2017** [comment]
Thanks a lot for the insights and the quick reply 🔥 I will check it out.
