### ISSUE TITLE
How to recommend items for new user. User is not in training data. 

### ISSUE THREAD

**Issue by 2mrdaya** [jfkirk/tensorrec#83]
Hi @jfkirk,

How to recommend items for new user. User is not in training dataset? and how to show new similar items to user. Please provide example with sample data.?

**Comment by jfkirk** [comment]
Hey @2mrdaya ! You can recommend items for users who were not in the training dataset -- just provide their features as the `user_features` argument to whichever `predict` method you are using. There is no constraint that a user had to be in the training data to be predictable.

Does that help?

**Comment by jfkirk** [comment]
Hey @2mrdaya -- I'm going to close this issue. If you have more questions, please open a new one. Thanks!
