### ISSUE TITLE
make_initializer Error

### ISSUE THREAD

**Issue by 2mrdaya** [jfkirk/tensorrec#84]
I am getting the below error
![image](https://user-images.githubusercontent.com/14895891/43132353-23db2950-8f59-11e8-992b-6482d57e8f35.png)
My code is given below
`import numpy as np
import tensorrec
import pandas as pd
import scipy
from scipy.sparse import csr_matrix
# Build the model with default parameters
model = tensorrec.TensorRec()

# Generate some dummy data
interactions, user_features, item_features = tensorrec.util.generate_dummy_data(
    num_users=10,
    num_items=15,
    interaction_density=.05
)
model.fit(ratings_sm, users_sm, news_sm, epochs=5, verbose=True)
#Test data fort single user
users_sm_test = csr_matrix(([.8],([0], [0])), shape=(1,200))
news_sm_test = csr_matrix(([.7],([0], [0])), shape=(1,200))
#Predict
model.predict(user_features=users_sm_test, item_features=news_sm_test)`

**Comment by jfkirk** [comment]
Hi @2mrdaya -- This error your running in to comes up when `predict` is called before the model has been `fit`.

Given that you're running in a Jupyter notebook, sometimes the namespace can get polluted from cells executing out of order. Try re-starting the kernel and running the cells in order and let me know if the problem persists.

Also, in the code snippet you provided:
```model.fit(ratings_sm, users_sm, news_sm, epochs=5, verbose=True)```
ratings_sm, users_sm, news_sm are not defined

I should add an exception to make it more clear when predict() is called before the model has been fit -- assigning to myself.

**Comment by 2mrdaya** [comment]
Thanks James :+1: 
I need one more help to take it on the production. My problem is how to recommend items for new user (having features) but not have any interaction? This user is not in the training data. Should i need to create a function to find similar user first or this library has the functionality?

**Comment by jfkirk** [comment]
Great! I'm going to close this issue, and will help you out with the new user question on the other issue.
