### ISSUE TITLE
Interaction matrix

### ISSUE THREAD

**Issue by mboudiaf** [jfkirk/tensorrec#88]
Hi James,

First of all thank you for this amazing work you did. It surely simplifies my life a lot building my recommandation system. Just one question about the interaction matrix and more specifically about the values one can plug inside. For instance, if I have a matrix with values from -1 to +5 (integers only), and want to the system to understand that:  -1 = disliked, 0 = no interactions with the item, and from 1 to 5 = liked (5 being the most liked), can I simply pass this matrix as input as such ? Thanks in advance :)

**Comment by pierrehabte2017** [comment]
I had the exact same question. With the binary system (1 if liked, 0 otherwise) we are losing information (the items that the person did not like for instance). Would it make sense to use 1 for liked, 0 for no interaction, -1 if disliked in the interaction matrix ?

**Comment by pierrehabte2017** [comment]
Thanks a lot @jfkirk 🥇 !

**Comment by jfkirk** [comment]
Great! I'm going to close this issue for now. Feel free to open a new one with more questions.
