### ISSUE TITLE
Dependency on datasets causing issue

### ISSUE THREAD

**Issue by pt** [jfkirk/tensorrec#94]
I'm new to python and trying to run the examples. In doing so, I ran into an issue installing a dependency:

```(tensor2) MacBook:tensor2 parker$ pip install datasets
Collecting datasets
  Using cached https://files.pythonhosted.org/packages/cd/fe/4d2874473a753d59c83335691bd9532704f2605418a0d288a1d70fa003fc/datasets-0.0.9.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_d/k4vvqhjd3lsgdrh93xw07fbh0000gn/T/pip-install-VOsrZA/datasets/setup.py", line 10, in <module>
        with open(path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
      File "/Users/parker/tensor2/lib/python2.7/codecs.py", line 884, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/_d/k4vvqhjd3lsgdrh93xw07fbh0000gn/T/pip-install-VOsrZA/datasets/DESCRIPTION.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_d/k4vvqhjd3lsgdrh93xw07fbh0000gn/T/pip-install-VOsrZA/datasets/
(tensor2) MacBook:tensor2 parker$```

This error generally seems to be a configuration issue when it occurs with other packages, but other packages seem to work fine and I've tried a bunch of combinatoons of python (2.n, 3.6, 3.7 which has an incompatibility with tensorflow) and other libraries. It appears to just be an issue with datasets.

According to [this page](https://stackoverflow.com/questions/38163760/cant-install-datasets-package-via-pip), there's an issue with the datasets package itself.

What is the recommended way of pulling in and using this library?

**Comment by jfkirk** [comment]
Hey @pt -- I'm not familiar with the `datasets` package and its not an explicit TensorRec requirement. Do you know what component is trying to install `datasets`?

**Comment by pt** [comment]
Perhaps I'm confused. It looks to me like the datasets library is a dependency for all of your examples. The library is easy to install, but the examples don't work. I should've been more clear in my message above.

More generally, I'm struggling to get this working for me practically (being new to TF/ML). It would be great to see a simple sample app that uses tensorrec to expose a REST api, and demonstrates batch processing + incremental model updates with large-ish data sets, which is realistic for most users.

Thanks for what you've built though. It's interesting and I'm sure if I understood how to use it it would achieve your goals.

**Comment by jfkirk** [comment]
Ahh -- the examples import a module within the project called `test.datasets` which is distinct from the python package `datasets`. It looks like the stack trace you posted is from an attempted installation of the python package.

You should be able to install all the dependencies you need using the `requirements.txt` and `requirements_examples.txt` files.

`pip install -r requirements.txt`
`pip install -r requirements_examples.txt`

Give that a shot and try running the examples. I'll leave this issue open if you hit any more roadblocks.

**Comment by pt** [comment]
Will do, thanks.
