### ISSUE TITLE
WMRB vs WARP

### ISSUE THREAD

**Issue by eggie5** [jfkirk/tensorrec#97]
WMRB is supposed to be WARP adapted for a batch setting right? According to my movie lens tests, the difference seems a bit large:

10D Embeddings, 10 Epochs:
WARP p@10: 0.110
WMRB p@10: 0.032

Test: https://gist.github.com/eggie5/863133def026a1dc0bf43c4ba3faaefd

Any idea why?

**Comment by jfkirk** [comment]
Hey @eggie5 ! Thanks for trying this out. There are a few factors at play here:

WMRB isn't _exactly_ WARP, though they're quite close. The difference don't explain the whole difference you're seeing, but the significantly higher variance of the rank estimator in WARP could be impactful when training for such a short period (only 10 epochs). This difference flattens out a bit over a longer period -- I tried 1000 epochs.

The LightFM MovieLens method returns all movie ratings between [1, 5], but the default arg for TensorRec's MovieLens method trims the results down to [4, 5]. This removes ~half of the interactions.

Also, by default LightFM does not use the `genre_features` from MovieLens but TensorRec does. Simple linear models with no feature engineering tend to do worse with these kinds of categorical features than with no features at all.

I tried running them both for 1000 epochs and tweaked your LightFM code to be closer to what TensorRec is seeing:

```
from lightfm import LightFM
from lightfm.evaluation import precision_at_k
import numpy as np
from lightfm.datasets import fetch_movielens

movielens = fetch_movielens(min_rating=4.0, genre_features=True)

train = movielens['train']
test = movielens['test']
item_features = movielens['item_features']

model = LightFM(loss='warp')
model.fit(train, epochs=1000, item_features=item_features)

test_precision = precision_at_k(model, test, item_features=item_features, k=10).mean()

print('p@10: %.2f' % (test_precision))
```

LightFM: p@10: 0.07
TensorRec: p@10: 0.06445

These results are closer to what I'd expect. What do you think?

**Comment by eggie5** [comment]
Thanks for the thoughtful reply. Indeed, I failed in removing all the dependent variables from the test. Particularly, the LFM model was training on **more** data as you pointed out. I updated my test with `min_rating=4.0` and now the two tests are converging around the same value. 

LightFM     WARP:  p@10: 0.071
TensorRec WMRB: p@10: 0.067

**Comment by jfkirk** [comment]
Hey @eggie5 -- to disable the user/item features, you can just throw away the user/item features that come back from the dataset generator. 

TensorRec still expects user/item features, so you can then pass in identity matrices of shape [n_users, n_users] and [n_items, n_items].

**Comment by jfkirk** [comment]
@eggie5 That's definitely a big constraint -- I've mostly been working on CPU environments because, unless I'm using deep representation graphs, there was no appreciably benefit to applying GPUs. Do you know of any good way I could try to dodge this densification?
